### ISSUE TITLE
Feature request: Pagination 

### ISSUE THREAD

**Issue by imranpollob** [markhorn-dev/astro-sphere#10]
For the blog page currently there is no pagination. For a large number of blog posts it's necessary to paginate the contents. Could you please add the feature?

**Comment by markhorn-dev** [comment]
I might be able to address this in the future but now at the moment. 

I'm pretty busy with a large project at the moment, and working a second job to make ends meet ... but I wanted to at least respond.

I initially used pagination, but being that dynamic filters are being used for posts I removed it.

For example if you have 3 category tags. There are N combinations of filters you could select. In this case 3^2 combinations = 9. But this grows considerably if you have more combinations like say 10 tags. 10^2 = 1024.

Astro is going to want to build 1024 static pages just for the blog list.

To make pagination work, I need to:

- Change rendering to SSR so data is fetched on demand (this I don't want to do)

- Remove dynamic filtering. (Can only select one tag at a time. This will still generate N categories of pages but would be way less). Some users may still want to filter by multiple categories.

- Alternate approach, could add a load more posts button, where the initial page is static and load say 10 items. At the bottom of the list if the list is truncated , click a more button to load 10 more. Many sites use this approach for static content.

**Comment by imranpollob** [comment]
Thanks for the detailed response. I understand the problem more clearly now. I implemented single tag filtering for now. Lazy loading of posts could be a future solution.
