### ISSUE TITLE
Content not displayed on mobile

### ISSUE THREAD

**Issue by VladYashin** [markhorn-dev/astro-sphere#3]
Hi there,

I tried to open your deployed website using the LinkedIn & Telegram built-in browsers on mobile and encountered the following screen:

![940612d4-5cab-42e8-9f6c-31456ed11b69](https://github.com/markhorn-dev/astro-sphere/assets/61877876/42b7e39d-24b4-4f6d-b9b3-e1c9e23de632)

The desktop version works perfectly fine. I think there might be an issue with the fonts, but I'm not certain...

P.S. I am currently building my website using your template and have spent at least 10+ hours trying to fix the issue, unfortunately without success.

P.P.S. This is one of the greatest, if not the greatest, Astro templates out there! 🚀🚀🚀

**Comment by VladYashin** [comment]
To ensure it's replicable for you:

1. Share your website through direct messages on Twitter or LinkedIn (https://astro-sphere-demo.vercel.app/).
2. Attempt to open it

**Comment by VladYashin** [comment]
To ensure it's replicable for you:

Share your website through direct messages on Twitter or LinkedIn (https://astro-sphere-demo.vercel.app/).
Attempt to open it

**Comment by markhorn-dev** [comment]
Has this been resolved?

**Comment by VladYashin** [comment]
Hi Mark, 

Yeah, I fixed this. The problem was with the fonts. I replaced your custom fonts with the same fonts from [Google](https://fonts.google.com/specimen/Atkinson+Hyperlegible) and it finally resolved the issue.

You can check my website here: iamvladyashin.com

Thanks for your template! Great work, buddy! 🚀

**Comment by markhorn-dev** [comment]
Thanks! Glad it's working for you. Looks good.
