### ISSUE TITLE
Inline markdown code shows backticks

### ISSUE THREAD

**Issue by Michaelryang** [markhorn-dev/astro-sphere#7]
Hello - I've been trying to figure out where the setting for this is in the project, but currently backticks are explicitly shown instead of being hidden for `inline code`. Code blocks look like how you'd expect.

I'm not sure if this is intended so I opened this issue. Example of what I mean below:

![image](https://github.com/markhorn-dev/astro-sphere/assets/6279102/fad9f283-a241-4e6a-8e24-eb0ab8e4aa26)

**Comment by markhorn-dev** [comment]
This is default behavior of the tailwind typography plugin. They can be removed several ways. See [here](https://github.com/tailwindlabs/tailwindcss-typography/issues?q=is%3Aissue+is%3Aclosed+backticks)

**Comment by Michaelryang** [comment]
Thank you, I figured it out. I really like the site by the way, keep up the good work.
